name: Testing multiple release actions with different artifacts

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update-release.yaml'

jobs:
  test-release1:
    name: Test release 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            example-artifact1.txt

  test-release2:
    name: Test release 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            example-artifact2.txt