name: Testing multiple release actions with different artifacts

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update-release-softprops.yaml'

jobs:
  test-release1:
    name: Test release 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "marvin"
          prerelease: true
          target_commitish: ${{ github.sha }}
          files: |
            example-artifact1.txt

  test-release2:
    name: Test release 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "marvin"
          prerelease: true
          target_commitish: ${{ github.sha }}
          files: |
            example-artifact2.txt
